version-template: 'v$MAJOR.$MINOR'
name-template: '$NEXT_MINOR_VERSION Release'
tag-template: '$NEXT_MINOR_VERSION'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  ## Changes

  $CHANGES