on:
  workflow_call:
    inputs:
        dir:
          type: string
          required: true
          description: Output directory
        config:
          type: string
          required: true
          description: Output directory
        schema:
          type: string
          required: true
          description: Output directory
        board:
          type: string
          required: true
          description: Output directory
      

jobs:
  Diff:
    name: Generate PCB & Schematic diffs
    runs-on: ubunutu-latest
    env:
        DIFF_OLD: ${{ github.event_name == 'pull_request' && format('{0}/{1}', 'origin', github.base_ref) || '' }}

    steps:
    - id: get_last_release_tag
      name: Get Last release tag name
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      run: |
        if [ -z ${{ env.DIFF_OLD }} ]
        then
          RELEASE_TAG=$(gh release ls --exclude-drafts --exclude-pre-releases --json tagName --jq '.[0].tagName')
          if [ -z "$RELEASE_TAG"]
          then
            RELEASE_TAG="KIBOT_LAST-1"
          fi
          echo "TAG_NAME=$RELEASE_TAG >> "$GITHUB_OUTPUT"
        else
          echo "TAG_NAME=${{ env.DIFF_OLD }}" >> "$GITHUB_OUTPUT"
        fi

    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: INTI-CMNB/KiBot@v2_k8
      name: PCB & Schematic Diff
      with:
        dir: ${{ env.OUTPUT_DIR }}
        config: ${{ env.KIBOT_CFG }}
        schema: ${{ env.SCHEMA_FILE }}
        board: ${{ env.PCB_FILE }}
        skip: erc,drc
        verbose: ${{ vars.VERBOSE_LEVEL != '' && vars.VERBOSE_LEVEL || 0 }}
        targets: >-
            -E DIFF_OLD='${{ steps.get_last_release_tag.outputs.TAG_NAME }}'
            pcb_diff sch_diff

    - name: Upload PCB & Schematic Diffs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: Diff
        path: ${{ env.OUTPUT_DIR }}/Diff/