name: "Upload Release Assets"

# Controls when the action will run.
on:
  workflow_call:
    

permissions:
  contents: write

jobs:
  uploadAssets:
    name: Upload Assets to release
    runs-on: ubuntu-latest
    env:
      zip3d: 3D Models-${{ github.ref_name }}.zip
      zipfab: Fabrication-${{ github.ref_name }}.zip
      zipbom: BoMs-${{ github.ref_name }}.zip
      zipprints: PCB and Schematic printout-${{ github.ref_name }}.zip
      jlcpcb: JLCPCB Assembly-${{ github.ref_name }}.zip
    steps:
      - id: download
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
      - run: ls -lR

      - id: zip3d
        run: zip -r -5 '${{ env.zip3d }}' 3D

      - id: zipfab
        run: zip -r -5 '${{ env.zipfab }}' Gerbers Drill

      - id: zipbom
        run: zip -r -5 '${{ env.zipbom }}' BoM

      - id: zipprints
        run: zip -r -5 '${{ env.zipprints }}' PCB Schematic

      - id: jlcpcb
        run: zip -r -5 '${{ env.jlcpcb }}' JLCPCB

      - id: upload_assets
        name: Upload assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ env.zip3d }}
            ${{ env.zipfab }}
            ${{ env.zipbom }}
            ${{ env.zipprints }}
            ${{ env.jlcpcb }}
          generate_release_notes: false